name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App

        run: npx ng build --base-href /Quiz_Game/

      - name: Copy index.html to 404.html
        run: cp dist/quiz-game/browser/index.html dist/quiz-game/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/quiz-game/browser
          branch: gh-pages